SHMUDataset:
  # Absolute path to the list containing dates used for training, validation and testing
  # The path can contain {split} that is replaced with train/test/valid
  date_list: "/data/maly_javornik_CMAX_60k_2/maly_javornik_new_sampling/metadata_lcnn_{split}.h5"
  # path and filename can contain the following tokens:
  # {year:*}, {month:*}, {day:*}, {hour:*}, {minute:*}, {second:*}
  # Path to archive
  path: "/data/maly_javornik_CMAX_60k_2/maly_javornik_new_sampling"
  # Filename format
  filename: "{year}{month:02d}{day:02d}{hour:02d}{minute:02d}.h5"
  # Importer used to load composites, options: h5
  importer: h5
  # Number of frames used as input
  input_block_length: 6
  # Number of frames that are predicted
  prediction_block_length: 6
  # Timestep of the data in minutes
  timestep: 5
  # Bounding box used as Python indices
  # written as [x1, x2, y1, x2] that corresponds to image[x1:x2, y1:y2]
  bbox: [2, 338, 2, 338]
  # Original Image size
  image_size: [340, 340]
  # Image size after bbox
  bbox_image_size: [336, 336]
  # Input image size, can contain upsampling
  input_image_size: [336, 336]
  # Upsampling method
  upsampling_method: average
  # Values for scaling to grayscale (the 0-1 range)
  min_val: -16.948421478271484
  max_val: 70
  transform_to_grayscale: true
