SHMUDataset:
  # Absolute path to the list containing dates used for training, validation and testing
  # The path can contain {split} that is replaced with train/test/valid
  date_list: "/data/maly_javornik_CMAX_60k_2/maly_javornik_new_sampling/metadata_lcnn_{split}.h5"
  # path and filename can contain the following tokens:
  # {year:*}, {month:*}, {day:*}, {hour:*}, {minute:*}, {second:*}
  # Path to archive
  path: "/data/lagrangian_data/SHMU_6_6_v2/{year}/{month:02d}/{day:02d}"
  # Filename format
  filename: "{commontime:%Y%m%d%H%M}_shmu_lagrangian.h5"
  # Importer used to load composites, options: pgm_gzip
  importer: lagrangian_h5
  # Number of frames used as input
  input_block_length: 6
  # Number of frames that are predicted
  prediction_block_length: 6
  # Timestep of the data in minutes
  timestep: 5
  # Bounding box used as Python indices
  # written as [x1, x2, y1, x2] that corresponds to image[x1:x2, y1:y2]
  bbox: none
  # bbox: null
  # Original Image size
  image_size: [336, 336]
  # Image size after bbox
  bbox_image_size: [336, 336]
  # Input image size, can contain upsampling
  input_image_size: [336, 336]
  # Upsampling method
  upsampling_method: average
  transform_to_grayscale: true
  # Whether to apply differencing to the data.
  # Note that if true, input block length is reduced by 1
  apply_differencing: True
  # data normalization method, options: log, log_unit, none
  normalization_method: none
  # Cut-off value for differenced mm/h values before transforming to [0,1] interval
  log_unit_diff_cutoff: 250
